services:
  postgres:
    image: postgres:14
    container_name: mlflow-postgres
    restart: always
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mlflow:
    build: .
    container_name: mlflow-server
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    command: >
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow
      --artifacts-destination ${MLFLOW_DEFAULT_ARTIFACT_ROOT}
      --serve-artifacts
      --host 0.0.0.0
      --port 5000
      --allowed-hosts localhost:5000,host.docker.internal:5000,127.0.0.1:5000

  nginx:
    image: nginx:latest
    container_name: mlflow-nginx
    restart: always
    depends_on:
      - mlflow
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro