services:
  postgres:
    image: postgres:14
    container_name: mlflow-postgres
    restart: always
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mlflow:
    build: .
    container_name: mlflow-server
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    command: >
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow
      --artifacts-destination s3://mlflow-artifact-demo-bucket
      --serve-artifacts
      --host 0.0.0.0
      --port 5000

